# Generated by Django 3.2.9 on 2022-01-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='tytul',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
