# Generated by Django 3.2.9 on 2022-02-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodatkoweInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(4, 'Elektronika'), (2, 'Dom'), (0, 'Inne'), (3, 'Zdrowotne'), (1, 'Samochód')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, default='')),
                ('gwiazdki', models.PositiveSmallIntegerField(default=5)),
                ('ubezpieczenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubezpieczenia.ubezpieczenie')),
            ],
        ),
        migrations.CreateModel(
            name='Obiekt_ubezpieczony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('ubezpieczenie', models.ManyToManyField(related_name='obiekt_ubezpieczony', to='ubezpieczenia.Ubezpieczenie')),
            ],
        ),
    ]
