# Generated by Django 3.2.9 on 2022-02-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0002_dodatkoweinfo_obiekt_ubezpieczony_ocena'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubezpieczenie',
            name='data_zakonczenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Samochód'), (4, 'Elektronika'), (2, 'Dom'), (0, 'Inne'), (3, 'Zdrowotne')], default=0),
        ),
    ]
