# Generated by Django 3.2.9 on 2022-02-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0004_auto_20220206_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Elektronika'), (0, 'Inne'), (3, 'Zdrowotne'), (2, 'Dom'), (1, 'Samochód')], default=0),
        ),
    ]
