# Generated by Django 3.2.9 on 2022-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0006_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (1, 'Samochód'), (2, 'Dom'), (4, 'Elektronika'), (3, 'Zdrowotne')], default=0),
        ),
    ]
