# Generated by Django 4.0.2 on 2022-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0009_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubezpieczenie',
            name='kategoria',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Samochód'), (3, 'Zdrowotne'), (2, 'Dom'), (4, 'Elektronika'), (0, 'Inne')], default=0),
        ),
    ]
